spring:
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: azure-openai
      embedding: azure-openai
      image: azure-openai
    # AI provider configuration
    azure.openai:
      chat:
        options:
          temperature: 1.0
          deployment-name: gpt-4o
      image.options:
        deployment-name: dall-e-3
        model: dall-e-3
      api-key:
      endpoint: https://{your-resource-name}.openai.azure.com