spring:
  application.name: RecipeFinder
  autoconfigure.exclude: org.springframework.ai.autoconfigure.azure.openai.AzureOpenAiAutoConfiguration
  ai:
    ollama:
      chat.model: llama3
      embedding.model: llama3
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
server.tomcat.max-swallow-size: -1
app:
  always-available-ingredients: wine,salt,pepper,olive oil,broth,rice
  available-ingredients-in-fridge: salmon,zucchinis
---
spring:
  config.activate.on-profile: ollama-compose
  docker.compose.profiles.active: ollama
---
spring:
  config.activate.on-profile: azure
  autoconfigure.exclude: org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration
  ai.azure.openai:
    chat.enabled: true
    image.options:
      deployment-name: Dalle3
      model: dall-e-3
