spring:
  application.name: RecipeFinder
  ai:
    model:
      chat: ollama
      embedding: ollama
      image: none
      audio:
        speech: none
        transcription: none
      moderation: none
    ollama:
      chat:
        model: llama3.2
        options.temperature: 0.5
      embedding.model: llama3.2
    vectorstore.redis.initialize-schema: true
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
server.tomcat.max-swallow-size: -1
spring.data.redis:
  host: localhost
  port: 6379
  username:
  password:
app:
  available-ingredients-in-fridge: bacon,onions
logging.level.org.springframework.ai.chat.client.advisor: DEBUG