spring:
  application.name: RecipeFinder
  ai:
    openai.chat.enabled: false
    ollama.chat.model: llama3
    azure.openai:
        image.options:
          deployment-name: Dalle3
          model: dall-e-3