spring:
  ai:
    model:
      chat: openai
      embedding: openai
      image: openai
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 1.0
      image.options:
        model: dall-e-3
        size: 1024x1024
        style: natural
      api-key: